name: RecipeBot
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.0
  - requests
  - langchain
  - pip
  - pytorch
  - faiss-cpu
  - torchvision 
  - pytorch
  - pip:
    - transformers
    - jq
    - llama-index
    - llama-index-llms-ollama
    - llama-index-embeddings-huggingface
    - langchain==0.1.16
    - langchain-community==0.0.34
    - langchain-core==0.1.45
    - langchain-openai==0.1.3
    - langserve==0.1.0
    - langsmith==0.1.49
    - pydantic==1.10.13
    - uvicorn==0.29.0