name: RecipeBot
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.0
  - requests
  - langchain
  - pip
  - pytorch
  - faiss-cpu
  - torchvision 
  - pytorch
  - pip:
    - transformers
    - jq
    - llama-index
    - llama-index-llms-ollama
    - llama-index-embeddings-huggingface
